services:
  db:
    image: mysql:8
    restart: always
    env_file: .env
    environment:
      MYSQL_DATABASE:    ${MYSQL_DATABASE}
      MYSQL_USER:        ${MYSQL_USER}
      MYSQL_PASSWORD:    ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"  # <— host port 3307 → container 3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    ports:
      - "8001:8000" # <— host port 8001 → container 8000
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/healthz || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  db_data:
